name: discord
on:
    workflow_dispatch:
    release:
      types: [created]

jobs:
  discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send discord message
        uses: appleboy/discord-action@3a09d810d0b53b8911c5047f5d6a4bedd1809246 # master
        with:
          webhook_id: ${{ secrets.WEBHOOK_ID }}
          webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
          message: |
            Kings World **${{ github.ref_name }}** has been released!

            **Modrinth**:
            <https://modrinth.com/mod/kings-world/version/${{ github.ref_name }}>

            **GitHub**:
            <https://github.com/${{ github.repository }}/releases/tag/${{ github.ref_name }}>
